### ISSUE TITLE
Event Queue

### ISSUE THREAD

**Issue by dakom** [Pauan/rust-dominator#26]
What's the recommendation for storing events in a queue to be processed later?

`Box<dyn StaticEvent>` is not allowed since StaticEvent can't be made into a Trait Object

**Comment by Pauan** [comment]
What's your use case?

**Comment by dakom** [comment]
Game loop such as http://www.isaacsukin.com/news/2015/01/detailed-explanation-javascript-game-loops-and-timing

So all input events are collected and handled on the next tick, rather than immediately.

**Comment by Pauan** [comment]
You have a few options:

1. You can use `Box<dyn Any>` and then the [`downcast_`](https://doc.rust-lang.org/nightly/std/any/trait.Any.html#method.downcast_ref) methods to convert it back into a concrete type. I don't recommend this though. It's slow, rather clunky to work with, and error prone (only runtime type checking, no exhaustiveness checks).

2. Create a new trait with the methods you need, and then impl it for the event types. This is *really* not recommended, because it only works if all the event types share the same methods, so it's very inflexible.

3. You can create an enum:

   ```rust
   enum Event {
       MouseMove(events::MouseMove),
       MouseClick(events::Click),
       KeyDown(events::KeyDown),
       // ...
   }
   ```

   Or better yet, use semantically appropriate enum fields:

   ```rust
   enum Event {
       MouseMove { x: i32, y: i32 },
       MouseClick { x: i32, y: i32, button: events::MouseButton },
       KeyDown { key: String, ctrl: bool, shift: bool, alt: bool },
       // ...
   }
   ```

   This is what I recommend. It's very fast, it's zero allocation (no need for `Box`), it's extremely flexible, it's statically type safe, it gives you a more Rust-y type to work with (including exhaustive pattern matching), and it allows you to do some pre-processing of the events before converting them into an `Event`.

   [This](https://github.com/Pauan/tab-organizer/blob/c34e1d53aea9fe71c20531396e04ec458c6fc138/src/browser.rs#L672-L725) is what I use in tab-organizer to merge many events into a [single queue](https://github.com/Pauan/tab-organizer/blob/c34e1d53aea9fe71c20531396e04ec458c6fc138/src/browser.rs#L467-L468).
