### ISSUE TITLE
Change dependencies to minor version

### ISSUE THREAD

**Issue by dakom** [Pauan/rust-dominator#42]
Should Dominator not depend only on minor version of crates instead of patch version?

e.g. 

```
wasm-bindgen = "^0.2"
```

instead of:
```
wasm-bindgen = "0.2.48"
```

?

That way application code won't need to duplicate the dependency (unless I misunderstand Rust's package management system...)

**Comment by Pauan** [comment]
If you don't specify any operators then Cargo uses `^` by default, so these two are exactly the same:

```toml
wasm-bindgen = "0.2.48"
wasm-bindgen = "^0.2.48"
```

Since it's a `0.x` version, that means `>= 0.2.48 and < 0.3`

If you want to specify an exact version, you have to manually use `=`:

```toml
wasm-bindgen = "=0.2.48"
```

This is the opposite of npm, which uses `=` by default (and you have to manually use `^`).

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
